src/deprecations.ts
=> Fixing https://github.com/pixijs/pixi-sound/issues/12

src/filters/EqualizerFilter.ts, src/filters/StereoFilter.ts, src/filters/TelephoneFilter.ts, src/filters/index.ts, src/htmlaudio/index.ts, src/index.ts, src/webaudio/WebAudioInstance.ts, src/webaudio/WebAudioNodes.ts, src/webaudio/WebAudioUtils.ts, src/webaudio/index.ts
Fixes #40 
@finscn could you review this?
=> Need to use setValueAtTime instead of AudioParam value setter

src/webaudio/WebAudioContext.ts
=> Fixes issue with Android Chrome 55+

pixi-sound.d.ts
=> tsc: export as default module

src/utils/supported.ts
* Reworks `utils.supported` and `validateFormats()` to allow for runtime changes, so that people can experiment with formats not included in the library. 
* Updates `opus` check to handle how Firefox & Chrome actually specify their support.
* Potentially adds `caf` (I don't have Safari so can't check this) as Safari supports the `opus` codec in a .caf file.
=> Rework supported/validateFormats to allow runtime changes.

src/Sound.ts
=> Add PlayOptions start parameter support for sound sprites

src/interfaces/IMediaInstance.ts, src/webaudio/WebAudioInstance.ts
=> Add stricter types for event callbacks

src/webaudio/WebAudioInstance.ts, src/webaudio/WebAudioMedia.ts
=> Add workaround for AudioBufferSourceNode bug in older Chrome versions

examples/index.html, src/filters/StreamFilter.ts, src/filters/index.ts, test/suite.ts
- Resolves #179 
add `StreamFilter`
export `MediaStream` to be used in `MediaRecorder` api
=> add StreamFilter

src/Filterable.ts, src/Sound.ts, src/SoundLibrary.ts, src/utils/playOnce.ts, src/webaudio/WebAudioInstance.ts, src/webaudio/WebAudioNodes.ts
There are some JSDocs and codes don't match, this PR fixes that.
=> match JSDoc with code

src/SoundLibrary.ts, test/suite.ts
=> SoundLibrary.add takes AudioBuffer as source type

examples/client/index.js, examples/css/examples.css, examples/index.html
- Resolves #181 
Editing function to basic sample codes
It will be great if user can edit the sample codes and see the changed results by click the play button.
=> Editing function to basic sample codes

src/filters/DistortionFilter.ts, test/suite.ts
=> Fix DistortionFilter returning the correct amount

examples/index.html, src/Sound.ts, src/htmlaudio/HTMLAudioInstance.ts, src/webaudio/WebAudioInstance.ts, test/suite.ts
- Resolves #73 
- Resolves #54 
add `filters` to `PlayOptions` and `WebAudioInstance`
Please see the reference issues.
=> add filters to audio instance

src/Sound.ts
Closes #206
* Fixes crash when attempting to play a sound before it's done preloading
=> Fix issue when attempting to play a sound that's still preloading

src/SoundLibrary.ts, test/index.test.ts
Closes #136
Add option to SoundLibrary to see if any sound is playing
```ts
import { sound } from '@pixi/sound'
console.log('Sounds playing?', sound.isPlaying());
```
=> Add isPlaying option to SoundLibrary

.github/workflows/nodejs.yml, package.json, src/SoundLoader.ts
=> Ignore unsupported extensions with Loader plugin

src/utils/sineTone.ts
=> Fix: Correct math on sine-tone generation

.github/workflows/main.yml
Automatically uploads the dist files to the release when created.
=> Add upload to release

src/htmlaudio/HTMLAudioInstance.ts
=> Fix: Incorrect parameter with progress event on html instance
