- src/Filterable.ts
- src/Sound.ts
- src/SoundContext.ts
- src/SoundInstance.ts
- src/SoundLibrary.ts
- src/SoundNodes.ts
Adds global filters through the `PIXI.sound.filtersAll` API. Addresses issue #8.
Also adds support for an analyser node on the global context `PIXI.sound.context.analyser` which can be useful for doing visualizations.
> Adds support for global filters

- examples/index.html
- src/Sound.ts
- src/SoundInstance.ts
- src/SoundLibrary.ts
- src/SoundSprite.ts
- src/deprecations.ts
- test/index.js
* Adds `fadeIn` and `fadeOut` to play options.
* `play` now returns a Promise for getting the instance being played if the current sound has not been loaded yet.
* Fixes maintaining play options with `autoPlay`
* Deprecates the `loaded` property of Sound. Use the constructor or the play options instead.
* Deprecates the `complete` property of Sound. Use the constructor or the play options instead.
Implements feature #4
> Fading Play Options

- README.md
- src/Sound.ts
- src/SoundLibrary.ts
- src/webaudio/WebAudioMedia.ts
- test/index.js
Fixes #28
This removes loading WebAudio use Node's `fs` module. This was implemented in v1 for very specific reasons which are more edge-case now. It was only intended for Electron projects to not have the loading throttle Chrome events (like rendering). This functionality could easily be implement in projects by loading the the source as an `ArrayBuffer` and passing that to `PIXI.sound.add` or `PIXI.sound.Sound.from`.
```js
const fs = require("fs");
fs.readFile(url, (err: Error, data: Buffer) => {
const arrayBuffer = new ArrayBuffer(data.length);
const view = new Uint8Array(arrayBuffer);
for (let i = 0; i < data.length; ++i) {
view[i] = data[i];
}
const sound = PIXI.sound.Sound.from(arrayBuffer);
});
```
> Drops support for loading using fs.readFile

- pixi-sound.d.ts
- src/SoundLibrary.ts
- test/index.js
* Adds `PIXI.sound.close()` method to destroy/close/disconnect the AudioContext
* Adds `PIXI.sound.init()` method to re-create the AudioContext
* Removes `PIXI.sound.global()`, the global object is always defined
Addresses #33
cc @cursedcoder
> Adds methods to close/init library, removes opt-in global object

- src/SoundLibrary.ts
- src/loader/Loader.ts
- src/loader/LoaderMiddleware.ts
Since PixiSound overrides the Loader, it needs to provide a pass-thru method for `addPixiMiddleware` to not break other 3rd-party middleware with PixiJS.
cc @cursedcoder 
Fixes #37
> Support `addPixiMiddleware` for Loader override

- src/webaudio/WebAudioMedia.ts
Bug in the WebAudioMedia load call should have been prioritizing decoding audio over loading. Assets loaded with PIXI.loaders.Loader no longer load assets twice.
> PIXI.loaders.Loader loading WebAudioMedia twice

- src/webaudio/WebAudioInstance.ts
Fixes #46 
Verified in iOS Simulator running iOS 8.1. Demo now works without throwing an error.
> Fixes iOS 8 Bug

- src/webaudio/WebAudioContext.ts
Please refer to [Autoplay Policy Change](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio).
This is applied to Chrome 66+.
> Correspond to Autoplay Policy Change

- .travis.yml
- package-lock.json
- package.json
Use NPM 5's package-lock.json file to lock down dependencies when using Travis. Less brittle dependency tree. Also, upgrades Node.js on Travis to v8.
> Upgrade Travis to use node 8 and package lock

- src/webaudio/WebAudioContext.ts
ios11 safari's webkitOfflineAudioContext allows only 44100 Hz sample rate
if not set 44100 Hz, safari is throw exception "SyntaxError: The string did not match the expected pattern.."
>  Fixes iOS11 bug 

- examples/client/sprites.js
- examples/demo.html
- examples/filters.html
- examples/index.html
- examples/sprites.html
- src/Sound.ts
- src/sprites/SoundSprite.ts
- src/webaudio/WebAudioInstance.ts
I needed this feature quite badly so i've implemented it hopefully in a not-too-hacky way.
The loop option can be set either on the individual sound sprite definitions or the sound object.
I changed the example pixi versions because it didn't seem to work with Pixi v5.
> Sound sprite looping enabled for WebAudio

- src/webaudio/WebAudioNodes.ts
See [The ScriptProcessorNode Interface](https://www.w3.org/TR/webaudio/).
> if the value is 0, then the implementation will choose the best buffer size for the given environment, which will be constant power of 2 throughout the lifetime of the node.
> Select buffer size automatically by setting 0

- src/webaudio/WebAudioInstance.ts
- src/webaudio/WebAudioNodes.ts
Eliminates dependency on ScriptProcessorNodes for tracking audio playback progress. Made consistent with method used in legacy mode. 
ScriptProcessorNode is still available on-demand, at the same location it could be found previously, for those who need to do advanced processing.
Addresses [#104](https://github.com/pixijs/pixi-sound/issues/104)
> Don't depend on ScriptProcessorNode for update event

- pixi-sound.d.ts
> Fix for removing deprecations from pixi.js v5.2.0

- pixi-sound.d.ts
- src/Sound.ts
- src/SoundLibrary.ts
- src/htmlaudio/HTMLAudioInstance.ts
- src/webaudio/WebAudioInstance.ts
This adds a new `PlayOptions` property, "`wait`" to allow use of the `when` parameter of `AudioBufferSourceNode.start()`, which can provide for more precise timing of audio playback than triggering audio in sync with the regular JS event loop. This new property is also supported in legacy mode, for feature parity, but offers no performance advantage in that mode.
> Support delayed start for playback

- src/utils/supported.ts
- test/index.js
My previous PR was not fully functional, as `resolveUrl` imports `supported` by value and thus what it imports can't be changed. As such, we need to just modify `supported` in place.
> Fix updating supported extensions at runtime

- src/webaudio/WebAudioContext.ts
Reference: https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/decodeAudioData
decodeAudioData return value: Void, or a Promise object that fulfills with the decodedData.
> Fixes unhandledRejection by decodeAudioData

- src/webaudio/WebAudioInstance.ts
- src/webaudio/WebAudioMedia.ts
After prolonged loading/unloading sounds, iOS Safari (and likely any other browser on iOS) will crash ("This page was reloaded because there was a problem"), because of an internal leak related to AudioBufferSourceNodes. The problem was fixed in SoundJS in this way: https://github.com/CreateJS/SoundJS/pull/203
The referenced solution replaces the buffer with a 1-sample long buffer, wrapped in a try-catch to avoid FF/Chrome exceptions for modifying buffer. My solution replaces it with `null`, and does not require a try-catch in major current browsers. At the time of the referenced solution, it was alleged that setting `buffer` to null will cause an exception, but on current platforms, I have not found this to be the case. This code has been tested on recent versions of Safari, Firefox, …
> Dereference AudioBufferSourceNode to fix iOS memory leak

- src/webaudio/WebAudioInstance.ts
- src/webaudio/WebAudioMedia.ts
same as #160, but for pixi-sound v2
> Dereference AudioBufferSourceNode to fix iOS memory leak V2

- src/interfaces/IMediaInstance.ts
Fixes #165
I changed the `IMediaInstance.off` handler type to match the one in `EventEmitter3`. This fixes the type incompatibility with strict mode when trying to assign `HTMLAudioMedia` to `IMedia` (and other similar cases).
Note that the incompatibility was most likely due to the missing `?` in `fn: Function`, which with strict null checks types the variable as `Function | undefined` instead of just `Function` but I went ahead and changed it to `(...args: any[]) => void` to get rid of the linter hack. That type should be compatible with anything that you can pass to `on` and `once` so we should be good.
> Fix IMediaInstance interface event off callback type

- src/Sound.ts
- src/webaudio/WebAudioMedia.ts
- test/suite.ts
- Resolves #177 
`Sound.from` can take `AudioBuffer` as `source`
To support `AudioBuffer` to be played
> add AudioBuffer as source of Sound

- src/Sound.ts
- test/suite.ts
Fixes #144
This feature addition allows passing `singleInstance` property to the play function. This works like the Sound property by the same name, but is play specific.
```js
const instance = sound.play('something', { singleInstance: true });
```
> Add singleInstance to play options

- global.d.ts
- package-lock.json
- package.json
- scripts/injectGlobalMixins.ts
- tsconfig.json
In PixiJS 6.1+ mixin typings for LoaderResource is support. This allows proper typings when referencing the LoaderResource object directly from the Loader. E.g.:
```ts
import { Loader } from 'pixi.js';
import '@pixi/sound';
const loader = new Loader();
loader.add('myMusic', 'myMusic.mp3');
loader.load((ldr, resources) => {
resources.myMusic.sound // <-- `sound` typed as Sound object
});
> Add support for GlobalMixins

- package-lock.json
- package.json
- src/filters/index.ts
- src/htmlaudio/index.ts
- src/index.ts
- src/utils/index.ts
- src/webaudio/index.ts
* Upgraded API Extractor to support exporting namespaces (`import * as ns from './file'`) this previously wasn't possible and required a bunch of ugly workarounds. Those have been removed.
> Remove workaround for namespace exports

- src/webaudio/WebAudioContext.ts
I got a report from a user of my web app, which depends on pixi sound, that in their Firefox browser it does not work. On the user's browser console, there was a log like the following:
`Uncaught DOMException: OfflineAudioContext constructor: Sample rate 384000 is not in the range [8000, 192000]`
I found that this happens because on the user's Firefox browser, `new AudioContext().sampleRate` eqauls `384000`,
and the pixi sound source passes this value to the `OfflineAudioContext` constructor without checking whether the value is in a valid rage.
I found that [8000, 96000] can be a valid range:
https://www.w3.org/TR/webaudio/#dom-offlineaudiocontext-offlineaudiocontext-numberofchannels-length-samplerate
https://www.w3.org/TR/webaudio/#dom-baseaudiocontext-createbuffer
This PR includes a …
> Fix Uncaught DOMException in Firefox

- src/webaudio/WebAudioContext.ts
Safari likes to reject the promise with null, giving us an error when we try to read the `message` field of null
https://stackoverflow.com/a/66453990
> Fixing error when safari rejects with null

- package-lock.json
- package.json
- src/SoundLoader.ts
- src/index.ts
* Supports the `extensions` API available in PixiJS 6.5.0
* v4 of PixiJS Sound will not be supported in v7, a new major release, this restricts the peers to <7
Fixes #210
> Support extensions API

- examples/index.html
- src/Sound.ts
- src/SoundLibrary.ts
Closes #227
Now instead of using Assets, you can provide multiple URLs
```ts
import musicOpus from './assets/audio/music.opus';
import musicM4a from './assets/audio/music.m4a';
import { sound } from '@pixi/sound';
sound.add('music', [musicOpus, musicM4a]);
```
The above is a shorthand for:
```ts
sound.add('music', { url: [musicOpus, musicM4a] });
```
> Provide alternative resolver option for bundlers

- src/webaudio/WebAudioContext.ts
Close #126
* Mobile devices now handle suspend/resume correctly
* All browser will pause/resume WebAudio context on blur/focus
> Fix mobile handling interruptions

- src/filters/DistortionFilter.ts
- src/filters/EqualizerFilter.ts
- src/filters/Filter.ts
- src/filters/MonoFilter.ts
- src/filters/ReverbFilter.ts
- src/filters/StereoFilter.ts
- src/filters/StreamFilter.ts
- src/filters/TelephoneFilter.ts
User on Discord had problems with transpiling with Babel with `@babel/plugin-transform-parameters` because of the conditional super() calls with the filters. This PR refactors the constructors to rework how to deal with legacy. 
```js
class DistortionFilter extends Filter {
constructor(amount = 0) {
var __super = (...args) => {
super(...args);
};
if (getInstance().useLegacy) {
__super(null);
return;
}
const { context } = getInstance();
const distortion = context.audioContext.createWaveShaper();
__super(distortion);
this._distortion = distortion;
this.amount = amount;
}
}
```
```js
class DistortionFilter extends Filter {
constructor(amount = 0) {
let distortion;
if (!getInstance().useLegacy) {
const { audioContext } = getInstance().context;
distortion = audioContext.createWaveShaper();
} …
```
> Fix difficulty transpiling filters

- src/SoundLibrary.ts
- src/webaudio/WebAudioContext.ts
Fixes #243 
Provide a flag to opt-out of auto-pause behavior. 
```js
import { sound } from '@pixi/sound';
sound.disableAutoPause = true;
```
or
```js
PIXI.sound.disableAutoPause = true;
```
> Add disableAutoPause option

- src/Sound.ts
Coincidentally stumbled on this: The second example from [here](https://pixijs.io/sound/examples/index.html#section-filetypes) is throwing in Safari (17.0) because it will just try to play the ogg file even though Safari does not support oggs.
It would now throw synchronously if no supported file is found. Previously a Promise got rejected, because the file could not be decoded. Could this change be a problem?
> Let preferUrl respect supported formats
